package cu.jaco.petstore.retrofit

import cu.jaco.petstore.retrofit.utils.RetrofitClient
import io.swagger.petstore.ApiClient
import io.swagger.petstore.api.StoreApi
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class PetStoreClient @Inject constructor() : RetrofitClient<StoreApi>() {

    override fun serviceCreator(): StoreApi {
        val client = ApiClient()
        client.configureFromOkclient(providerOkHttpBuilder().build())
        return client.createService(StoreApi::class.java)
    }

    override fun headers(): HashMap<String, String> {
        val headers = HashMap<String, String>()
        headers["apikey"] = "eyJ4NXQiOiJOVGRtWmpNNFpEazNOalkwWXpjNU1tWm1PRGd3TVRFM01XWXdOREU1TVdSbFpEZzROemM0WkE9PSIsImtpZCI6ImdhdGV3YXlfY2VydGlmaWNhdGVfYWxpYXMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJDdWJhbkphY29AY2FyYm9uLnN1cGVyIiwiYXBwbGljYXRpb24iOnsib3duZXIiOiJDdWJhbkphY28iLCJ0aWVyUXVvdGFUeXBlIjpudWxsLCJ0aWVyIjoiMTBQZXJNaW4iLCJuYW1lIjoiUHJ1ZWJhIE9zdmVsIiwiaWQiOjYsInV1aWQiOiJmMmMxNjRjMy0wMmZlLTQzMDEtYmE3MS0wMDQxMTNhN2Q0NTEifSwiaXNzIjoiaHR0cHM6XC9cL2FwaW0udmlhamFuZG8udHJhbnNuZXQuY3U6NDQzXC9vYXV0aDJcL3Rva2VuIiwidGllckluZm8iOnsiVW5saW1pdGVkIjp7InRpZXJRdW90YVR5cGUiOiJyZXF1ZXN0Q291bnQiLCJncmFwaFFMTWF4Q29tcGxleGl0eSI6MCwiZ3JhcGhRTE1heERlcHRoIjowLCJzdG9wT25RdW90YVJlYWNoIjp0cnVlLCJzcGlrZUFycmVzdExpbWl0IjowLCJzcGlrZUFycmVzdFVuaXQiOm51bGx9fSwia2V5dHlwZSI6IlBST0RVQ1RJT04iLCJwZXJtaXR0ZWRSZWZlcmVyIjoiIiwic3Vic2NyaWJlZEFQSXMiOlt7InN1YnNjcmliZXJUZW5hbnREb21haW4iOiJjYXJib24uc3VwZXIiLCJuYW1lIjoiRGlzcG9uaWJpbGlkYWQiLCJjb250ZXh0IjoiXC9hdmFpbGFiaWxpdHlcLzEuMC4wIiwicHVibGlzaGVyIjoiYWRtaW4iLCJ2ZXJzaW9uIjoiMS4wLjAiLCJzdWJzY3JpcHRpb25UaWVyIjoiVW5saW1pdGVkIn1dLCJwZXJtaXR0ZWRJUCI6IiIsImlhdCI6MTYyMzMzNTU4NSwianRpIjoiNDZlMDU5MGEtOWY4OS00NDlkLTgyOGYtYjVhZGZkN2M5MjEwIn0=.enSZZR_ncuOam9swaIPkOqhujkO0vW8rqTvNUO7fMd4HyZZXtxuajPRg7NNuG9RfI7D3N3dY_zDy157jK_nvtkM4nUhjAKJa8QqdRrXpDiiVjiJVQChQO_yqvvwuM1xDBkhFjUeLBf9Up-tyzxYl4gU3kPxr25kuaNC8L9moWvqgntMkhLgghIJD9FnCPsXOha5gZI3O92RwjUv98Bidv6QXM7vGPfAUheocPbmdAl8Ay_lPoC5SHnrAOvtPyupF_utomveJ0oGAGz7tp6kuOZ6dT2HeSqq6DWBmwo8UPIpdc0nE-I28W7MGU3D1bBWPjBNQYIanIrk86TBJyvltAQ=="
        return headers
    }

}